before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
install:
    - sudo apt-get install -qq  g++-4.8 build-essential pmake cppcheck rats sparse
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - sudo apt-get install --allow-unauthenticated -qq clang-3.3
script: pmake NOLINT=
after_success:
  - cd regress && pmake && cd ..
  - pmake check
  - cppcheck --enable=all -q --std=c99 -Iinclude -Ilib `git ls-files *.c`
  - rats -l c `git ls-files *.c`
language: c
compiler: 
    - gcc
    - clang
branches:
  only:
    - master
